source 'https://rubygems.org'

# ruby '3.2.0' # Ensure this matches the version you plan to use

gem 'pry', group: :development

gem 'rspec', '~> 3.12.0'
gem 'rest-client', '~> 2.1'
gem 'dotenv', '~> 2.8', '>= 2.8.1'

gem 'rexml', '~> 3.2', '>= 3.2.6'
gem 'aws-sdk-s3', '~> 1.136'
gem 'aws-sdk-glue', '~> 1.157'
gem 'concurrent-ruby', '~> 1.2', '>= 1.2.2'